;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	ivy-forward-char
	ivy-next-line-or-history
	kill-region
	org-beginning-of-line
	org-end-of-line
	org-metaright
	org-self-insert-command
	swiper
	))

(setq mc/cmds-to-run-once
      '(
	down-list
	ivy-next-line
	org-demote-subtree
	org-insert-heading-respect-content
	))
